<!DOCTYPE html>
<html lang="ja">
<head>
  <meta charset="utf-8">
  <link rel="stylesheet" type="text/css" href="storage/app/plugins/ManagementView/public/css/table.css">
</head>
<body>
  <table class="left">
    <thead>
      <tr>
        <th scope="col">氏名</th>
        <th scope="col">所属</th>
        <th scope="col">原価</th>
        <th scope="col">備考</th>
        <th scope="col">７月</th>
        <th scope="col">８月</th>
        <th scope="col">９月</th>
        <th scope="col">１０月</th>
        <th scope="col">１１月</th>
        <th scope="col">１２月</th>
        <th scope="col">１月</th>
        <th scope="col">２月</th>
        <th scope="col">３月</th>
        <th scope="col">４月</th>
        <th scope="col">５月</th>
        <th scope="col">６月</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>井戸</td>
        <td>個人</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>古村</td>
        <td>個人</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>北村勇</td>
        <td>個人</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>榎本</td>
        <td>個人</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td colspan="4">派遣契約</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>服部</td>
        <td>スタイルフリー</td>
        <td></td>
        <td>個別契約書：単月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>村瀬</td>
        <td>ヨコタ</td>
        <td></td>
        <td>個別契約書：単月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>西尾</td>
        <td>ITP</td>
        <td></td>
        <td>個別契約書：３ヶ月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>西尾</td>
        <td>ITP</td>
        <td></td>
        <td>個別契約書：単月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>田中夏</td>
        <td>ビーネックス</td>
        <td></td>
        <td>個別契約書：単月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>岡本</td>
        <td>ウイングノア</td>
        <td></td>
        <td>個別契約書：単月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
      <tr>
        <td>金田</td>
        <td>アテナ</td>
        <td></td>
        <td>個別契約書：単月</td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    </tbody>
  </table>
</body>